In [1]:
import numpy as np
import colorama

from tetris_rl.env.tetromino import Tetromino

In [2]:
# def color_non_zero(x):
#     c = colorama.Fore.GREEN if x != 0 else colorama.Fore.RESET
#     return f"{c}{x:.0f}"

# np.set_printoptions(formatter={'float': color_non_zero})

In [3]:
j_tetromino = Tetromino("J")
j_tetromino.x = 3
j_tetromino.y = 1
_repr = j_tetromino.arr
height = j_tetromino.get_height()
width = j_tetromino.get_width()
playfield = np.zeros((20, 10))
_repr

array([[2, 0, 0],
       [2, 2, 2],
       [0, 0, 0]])

In [4]:
def init_playfield():
    r"""Initialize a test playfield."""
    playfield = np.zeros((20, 10))
    playfield[
        j_tetromino.y : j_tetromino.y + _repr.shape[0],
        j_tetromino.x : j_tetromino.x + _repr.shape[1],
    ] += _repr
    return playfield

In [5]:
def shift_left(arr: np.ndarray, amt: int) -> np.ndarray:
    r"""Shift the columns by the specified amount to the left."""
    for _ in range(amt):
        arr = np.roll(arr, -1, axis=1)
        arr[:, -1] = 0
    return arr

In [6]:
def shift_right(arr: np.ndarray, amt: int) -> np.ndarray:
    r"""Shift the columns by the specified amount to the right."""
    for _ in range(amt):
        arr = np.roll(arr, 1, axis=1)
        arr[:, 0] = 0
    return arr

In [7]:
def shift_down(arr: np.ndarray, amt: int) -> np.ndarray:
    r"""Shift the columns by the specified amount downwards."""
    for _ in range(amt):
        arr = np.roll(arr, 1, axis=0)
        arr[0, :] = 0
    return arr

In [8]:
# left collision
lc_playfield = init_playfield()
lc_playfield = shift_left(lc_playfield, 4)
lc_playfield

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
# right collision
rc_playfield = init_playfield()
rc_playfield = shift_right(rc_playfield, 5)
rc_playfield

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
# down collision
dc_playfield = init_playfield()
dc_playfield = shift_down(dc_playfield, 18)
dc_playfield

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.]])

In [28]:
def is_oob(arr: np.array, tetromino: Tetromino) -> bool:
    r"""Detect if the tetromino has gone out of bounds."""
    idx = tetromino.tetromino_idx
    width = tetromino.get_trimmed_width()
    height = tetromino.get_trimmed_height()
    print(np.sum(np.count_nonzero(arr, axis=1) / idx))
    h_check = np.sum(np.count_nonzero(arr, axis=1) / idx) >= height
    w_check = np.sum(np.count_nonzero(arr, axis=0) / idx) >= width
    print(w_check)
    print(h_check)
    return not h_check or not w_check

In [29]:
# check if the entire height is within bounds
idx = j_tetromino.tetromino_idx
h_check = np.sum(np.count_nonzero(lc_playfield, axis=1) / idx) >= height
h_check

np.False_

In [30]:
# check if the entire width is within bounds
idx = j_tetromino.tetromino_idx
w_check = np.sum(np.count_nonzero(lc_playfield, axis=0) / idx) >= width
w_check

np.False_

In [31]:
is_oob(lc_playfield, j_tetromino)

False
False


True

In [32]:
is_oob(rc_playfield, j_tetromino)

False
False


True

In [33]:
is_oob(dc_playfield, j_tetromino)

False
False


True

In [34]:
playfield = init_playfield()
playfield

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 2., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
is_oob(playfield, j_tetromino)

True
False


True